#enable the terminal colors
export CLICOLOR=1

#the default color scheme is "exfxcxdxbxegedabagacad"
export LSCOLORS=gxfxcxdxbxegedabagacad

alias arwa="cd ~/Vagrant/phpdevbox/www/theguide/"
alias aws="cd ~/Documents/Programming\ Workspace/Android\ Workspace/"
alias pws="cd ~/Vagrant/python/www/"
alias sws="cd ~/Downloads/Courses/Startup\ Engineering/Workspace/"

#adding brew python to the PATH
export PATH=$PATH:/usr/local/share/python

# virtualenv should use Distribute instead of legacy setuptools
#export VIRTUALENV_DISTRIBUTE=true

# Centralized location for new virtual environments
#export PIP_VIRTUALENV_BASE=$HOME/Venvs

# pip should only run if there is a virtualenv currently activated
#export PIP_REQUIRE_VIRTUALENV=true

# cache pip-installed packages to avoid re-downloading
#export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
