#enable the terminal colors
export CLICOLOR=1

#the default color scheme is "exfxcxdxbxegedabagacad"
export LSCOLORS=gxfxcxdxbxegedabagacad

#increase the terminal history size
export HISTSIZE=2000

#aliases to easy change the most working directories
alias pws="cd ~/Vagrant/pyhome/www/"
alias rws="cd ~/Vagrant/ruby/www/"
alias www="cd ~/Sites/"

#grep alias to enable coloring all the time
alias grep='grep --color=auto'
alias la='ls -a'

#adding local/bin PATH before /bin PATH
export PATH="/usr/local/bin:$PATH"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

## Adding the phonegap android locally android sdk
export PATH=${PATH}:~/Documents/Android/ADT-Bundle/sdk/platform-tools:~/Documents/Android/ADT-Bundle/sdk/tools

##lincolnloop best practice structure
#alias django-best-practice="django-admin.py startproject --template=https://github.com/lincolnloop/django-layout/zipball/master --extension=py,rst,gitignore,example"
alias wget-website="wget --recursive --no-clobber --page-requisites --convert-links --no-parent $@"

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

move_to_trash(){
    if [ ! -d ~/.Trash/ ];then
        mkdir ~/.Trash
    fi
    if [[ -d $1 && $1 != '' ]];then
        mv $1 ~/.Trash/
    elif [[ -f $1 && $1 != '' ]];then
        mv $1 ~/.Trash/
    else
        echo "this is a custom .bash_profile wrapper around 'rm'"
        echo "use this rm to move files or directories to '~/.Trash/' directory"
    fi
}
alias rm=move_to_trash
